export interface CompanyIntel {
  description: string;
  ceo: string;
  keyProducts: string[];
  competitors: string[];
  moat: string;
  keyRisk: string;
}

const INTEL: Record<string, CompanyIntel> = {
  AAPL: {
    description: "Apple designs and sells consumer electronics, software, and services. The iPhone drives ~52% of revenue, but Services (App Store, Apple Music, iCloud, Apple TV+) are the highest-margin segment and the key growth engine.",
    ceo: "Tim Cook",
    keyProducts: ["iPhone 16 series", "Mac (Apple Silicon)", "Services / App Store", "AirPods / Vision Pro"],
    competitors: ["Samsung", "Google (Pixel / Android)", "Microsoft (Surface)"],
    moat: "Ecosystem lock-in: 2 billion active devices create an extraordinarily high switching cost. Services revenue is high-margin and recurring, insulating Apple from hardware cycles.",
    keyRisk: "iPhone concentration (~52% revenue) means any demand miss or China regulatory action is an earnings shock. US DOJ antitrust case on App Store could compress Services margins.",
  },
  MSFT: {
    description: "Microsoft operates across productivity software (Office 365), cloud infrastructure (Azure), gaming (Xbox / Activision), and enterprise software (Dynamics, LinkedIn). Azure is the highest-growth segment and the strategic battleground.",
    ceo: "Satya Nadella",
    keyProducts: ["Azure Cloud (AI / IaaS / PaaS)", "Microsoft 365 / Copilot", "GitHub Copilot", "Xbox / Game Pass"],
    competitors: ["Amazon AWS", "Google Cloud", "Salesforce", "Workday"],
    moat: "Azure plus Microsoft 365 create a near-unbreakable enterprise IT stack. GitHub Copilot and Copilot integration into Office give Microsoft the largest AI distribution channel in enterprise software.",
    keyRisk: "Azure growth deceleration — market is watching GPU supply constraints limiting AI inference revenue. Competition from AWS on price and Google on models is intensifying.",
  },
  GOOGL: {
    description: "Alphabet's Google generates 77% of revenue from Search advertising, but Cloud (GCP) is the fastest-growing segment. DeepMind's Gemini model is the company's primary bet on the AI transition.",
    ceo: "Sundar Pichai",
    keyProducts: ["Google Search / Advertising", "YouTube", "Google Cloud (GCP)", "Gemini AI Models"],
    competitors: ["Microsoft (Bing/Azure AI)", "Meta (advertising)", "Amazon AWS", "OpenAI (search disruption)"],
    moat: "Google Search has a ~90% global search share built on the world's largest web index and user behaviour data. YouTube is the #2 social media platform with exceptional monetisation.",
    keyRisk: "AI-powered search disruption (ChatGPT, Perplexity) threatening the Search moat is the existential risk. DOJ antitrust ruling forcing divestiture of Chrome or Android would be structurally damaging.",
  },
  META: {
    description: "Meta operates Facebook, Instagram, WhatsApp, and Threads — collectively reaching 3.3 billion daily users. Advertising is 98% of revenue. Reality Labs (Quest VR) burns ~$5B/year but is a long-term bet on spatial computing.",
    ceo: "Mark Zuckerberg",
    keyProducts: ["Facebook / Instagram Ads", "Reels", "WhatsApp Business API", "Meta AI / Llama", "Quest VR"],
    competitors: ["TikTok (ByteDance)", "Google (advertising)", "Snap", "X (formerly Twitter)"],
    moat: "Network effects at 3.3B daily users are unparalleled. Advantage+ AI ad targeting has rebuilt advertiser ROI post Apple ATT. Llama open-source strategy is winning developer mindshare.",
    keyRisk: "TikTok ban reversal creating a stronger competitor is the near-term upside/downside. Teen engagement decline on Facebook is a structural concern. EU regulatory fines (GDPR) are recurring.",
  },
  NVDA: {
    description: "NVIDIA designs GPUs and AI accelerator chips that power the global AI infrastructure buildout. The Data Center segment (H100/H200/B100 Blackwell) drives 87% of revenue and is growing >100% YoY. Gaming and Automotive are secondary.",
    ceo: "Jensen Huang",
    keyProducts: ["H100 / H200 / Blackwell GPU", "CUDA software platform", "NVLink / NVSwitch", "DGX AI systems"],
    competitors: ["AMD (MI300X)", "Intel (Gaudi)", "Google (TPUs)", "Amazon (Trainium)"],
    moat: "CUDA software ecosystem (1M+ developers) creates an extraordinary switching cost beyond hardware. Hyperscalers cannot quickly retrain their AI workloads away from CUDA-optimised code.",
    keyRisk: "US export restrictions on H100/H200/B100 to China directly cap the addressable market. Custom silicon from hyperscalers (Google TPU, Amazon Trainium) could reduce demand long-term.",
  },
  TSLA: {
    description: "Tesla designs and manufactures electric vehicles, energy storage systems (Powerwall/Megapack), and operates an AI/autonomy division (Optimus robot, Full Self-Driving). Automotive gross margins are under pressure from price cuts.",
    ceo: "Elon Musk",
    keyProducts: ["Model Y / Model 3", "Cybertruck", "Full Self-Driving (FSD)", "Megapack / Powerwall", "Optimus Robot"],
    competitors: ["BYD", "Rivian", "Ford / GM EV", "Volkswagen / Hyundai EV"],
    moat: "Supercharger network (60,000+ stalls), OTA software update capability, and vertically-integrated battery manufacturing are genuine advantages. FSD could be transformative if regulatory approval achieved.",
    keyRisk: "CEO political controversy affecting brand equity in Europe and California. BYD competitive pressure in China (Tesla's #2 market) is compressing average selling prices globally.",
  },
  AMZN: {
    description: "Amazon operates e-commerce, AWS cloud infrastructure, Prime subscription services, digital advertising, and Whole Foods. AWS contributes ~16% of revenue but ~60% of operating profit — it is the primary earnings engine.",
    ceo: "Andy Jassy",
    keyProducts: ["AWS (EC2, S3, Bedrock AI)", "Amazon Prime / Marketplace", "Prime Video", "Amazon Advertising"],
    competitors: ["Microsoft Azure", "Google Cloud", "Walmart (e-commerce)", "Alibaba"],
    moat: "AWS switching costs are extreme — enterprises that build on AWS face years of re-platforming to switch. Amazon's e-commerce flywheel (Prime, Marketplace, logistics) is self-reinforcing.",
    keyRisk: "AWS growth deceleration driven by customer cost optimisation. FTC antitrust scrutiny on marketplace practices. Grocery / Whole Foods remains loss-making and strategically unclear.",
  },
  MA: {
    description: "Mastercard operates a two-sided payment network connecting 3.3 billion cardholders with 100 million merchants in 200+ countries. Revenue is fee-based on transactions and cross-border volume — not credit exposure.",
    ceo: "Michael Miebach",
    keyProducts: ["Mastercard payment network", "Vynapse (open banking)", "Mastercard Send (P2P)"],
    competitors: ["Visa", "American Express", "PayPal / Venmo", "Apple Pay"],
    moat: "Network effects: merchants need Mastercard because cardholders have it; cardholders want it because merchants accept it. This flywheel has run for 55 years and is nearly impossible to replicate from scratch.",
    keyRisk: "Central bank digital currencies (CBDCs) or government-mandated payment rails bypassing card networks is the structural long-term threat. Real-time payment schemes (FedNow, UPI) gaining share.",
  },
  V: {
    description: "Visa is the world's largest payment network by volume, processing $14.8 trillion in annual payments. It charges fees on transactions without taking credit risk — the ultimate toll-booth business model.",
    ceo: "Ryan McInerney",
    keyProducts: ["Visa payment network", "Visa Direct (real-time P2P)", "Visa B2B Connect", "Cybersource (gateway)"],
    competitors: ["Mastercard", "American Express", "UnionPay (China)", "PayPal"],
    moat: "Visa's 4.1 billion cards and 100M merchant relationships make it the backbone of global commerce. Operating leverage is exceptional — 80% incremental margins as volumes scale.",
    keyRisk: "Merchant-led antitrust litigation (interchange fee cases) is the recurring legal overhang. Competition from Mastercard in premium card space and PayPal in digital commerce.",
  },
  ADBE: {
    description: "Adobe is the dominant creative software platform — Photoshop, Illustrator, Premiere, and the Creative Cloud subscription — plus the fast-growing Document Cloud (Acrobat/Sign) and Experience Cloud (marketing analytics). Firefly AI is the key growth catalyst.",
    ceo: "Shantanu Narayen",
    keyProducts: ["Creative Cloud (Photoshop, Premiere, Illustrator)", "Acrobat / Document Cloud", "Experience Cloud", "Adobe Firefly (generative AI)"],
    competitors: ["Canva (consumer creative)", "Figma (UI design)", "Microsoft (Office + Copilot)", "OpenAI (DALL-E / Sora)"],
    moat: "Industry-standard workflows create extreme switching costs — filmmakers, graphic designers, and marketers have spent years learning Adobe's tools. The Creative Cloud annual subscription is among the stickiest in SaaS.",
    keyRisk: "Canva democratising design with AI and Figma's collaborative model threaten the next generation of creatives choosing Adobe. The failed $20B Figma acquisition leaves Adobe without the leading UI design platform.",
  },
  CRM: {
    description: "Salesforce is the world's largest CRM platform, serving 150,000 companies across Sales Cloud, Service Cloud, Marketing Cloud, Commerce Cloud, and Slack. Agentforce (AI agent platform) is the company's transformational 2025 product.",
    ceo: "Marc Benioff",
    keyProducts: ["Sales Cloud (CRM)", "Service Cloud", "Agentforce (AI agents)", "Slack", "MuleSoft / Tableau"],
    competitors: ["Microsoft Dynamics", "HubSpot", "Zendesk / ServiceNow", "SAP CX"],
    moat: "Salesforce is deeply embedded in enterprise sales, service, and marketing workflows. The Agentforce autonomous agent platform gives Salesforce a first-mover advantage in agentic AI for enterprise CRM.",
    keyRisk: "Growth deceleration in core CRM markets. Microsoft Dynamics competition benefits from deep Office/Azure integration. Agentforce monetisation timeline uncertainty.",
  },
  NOW: {
    description: "ServiceNow is the enterprise workflow automation platform — its Now Platform connects IT, HR, customer service, and security operations across the largest global corporations. Pro Plus with AI is the highest-growth SKU.",
    ceo: "Bill McDermott",
    keyProducts: ["IT Service Management (ITSM)", "IT Operations Management", "HR Service Delivery", "Now Assist (AI)", "Security Operations"],
    competitors: ["BMC Software", "Atlassian (Jira)", "Salesforce Service Cloud", "Microsoft"],
    moat: "ServiceNow's platform becomes more embedded with each workflow automated — ripping it out requires migrating thousands of enterprise process automations. 1700 customers spend >$1M ARR.",
    keyRisk: "Hyperscalers (Microsoft, Salesforce) building competing workflow automation into their existing platforms. Valuation premium requires sustained 20%+ revenue growth.",
  },
  SNOW: {
    description: "Snowflake is a cloud data warehouse and data sharing platform built on a consumption-based model. It sits at the centre of enterprise data lakes and is expanding into data applications and AI model training workloads.",
    ceo: "Sridhar Ramaswamy",
    keyProducts: ["Snowflake Data Cloud", "Cortex AI (ML in SQL)", "Snowpark (developer framework)", "Data Clean Rooms"],
    competitors: ["Databricks (private)", "Google BigQuery", "Amazon Redshift", "Microsoft Fabric"],
    moat: "Snowflake's Data Sharing capability allows companies to share live data across organisations without data movement — creating network effects among its customer base of 9,000 companies.",
    keyRisk: "Databricks (private, $43B valuation) is an existential competitive threat. Consumption-based revenue model creates lumpy earnings — customer optimisation cuts revenue immediately.",
  },
  DDOG: {
    description: "Datadog is the leading observability and security platform for cloud infrastructure, monitoring logs, metrics, APM (application performance monitoring), and cloud security in one unified platform.",
    ceo: "Olivier Pomel",
    keyProducts: ["Infrastructure Monitoring", "APM (Application Performance)", "Log Management", "Cloud Security (CSPM/CWPP)", "LLM Observability"],
    competitors: ["Dynatrace", "New Relic", "Splunk (Cisco)", "Elastic"],
    moat: "Datadog's platform land-and-expand motion is powerful — customers start with one module and expand to 5+ products over time. Average contract value grows ~30%/year with product adoption.",
    keyRisk: "Hyperscalers bundling monitoring tools into cloud platforms (AWS CloudWatch, Azure Monitor) at lower price points. Competitive pressure from Dynatrace on enterprise accounts.",
  },
  CRWD: {
    description: "CrowdStrike is the leading cloud-native endpoint security platform. The Falcon platform protects endpoints, workloads, cloud, and identity using AI-trained on 1 trillion daily signals from 23,000 enterprise customers.",
    ceo: "George Kurtz",
    keyProducts: ["Falcon Endpoint Protection", "Falcon Identity Protection", "Falcon Cloud Security", "Falcon Intelligence (threat intel)"],
    competitors: ["Palo Alto Networks", "Microsoft Defender", "SentinelOne", "Zscaler"],
    moat: "Falcon's AI/ML trained on the world's largest threat intelligence dataset creates compounding accuracy advantages. The single-agent architecture is lighter and faster than legacy AV products.",
    keyRisk: "The July 2024 Falcon sensor update caused a global IT outage (8.5 million Windows systems). Customer trust restoration is ongoing — churn risk elevated for next 2 years.",
  },
  PANW: {
    description: "Palo Alto Networks is the largest cybersecurity pure-play, providing network security (NGFW), cloud security (Prisma Cloud), and AI-driven SOC operations (Cortex XSIAM). Platform consolidation is the key growth strategy.",
    ceo: "Nikesh Arora",
    keyProducts: ["Next-Gen Firewall (NGFW)", "Prisma SASE / Prisma Cloud", "Cortex XSIAM (AI SOC)", "Cortex XDR"],
    competitors: ["Fortinet", "CrowdStrike", "Zscaler", "Cisco (Splunk)"],
    moat: "Palo Alto's 'platformisation' strategy locks out competitors by bundling 50+ security products — customers get better security at lower total cost than buying point products.",
    keyRisk: "Platformisation involves giving away products for free upfront to displace competitors — this compresses near-term revenue growth and requires investor patience for 2–3 year payback.",
  },
  PLTR: {
    description: "Palantir builds AI and data analytics platforms for government intelligence agencies (Gotham) and commercial enterprises (Foundry, AIP). The US Commercial segment is the fastest-growing and the key bull case.",
    ceo: "Alex Karp",
    keyProducts: ["AIP (AI Platform)", "Foundry (commercial analytics)", "Gotham (government intelligence)", "Apollo (deployment ops)"],
    competitors: ["Databricks", "Microsoft Azure OpenAI", "AWS SageMaker", "Verint (government)"],
    moat: "US government relationships (classified contracts, FedRAMP) create a near-impossible competitive barrier. AIP's 'boot camp' sales model drives rapid enterprise adoption by showing live ROI.",
    keyRisk: "Government spending cuts (DOGE) directly threatening Palantir's largest revenue segment (~55% government). Commercial revenue needs to offset; current commercial RPO growth is promising but unproven at scale.",
  },
  NET: {
    description: "Cloudflare operates a global network of 300+ data centres that provide CDN, DDoS protection, Zero Trust security, serverless computing (Workers), and AI inference at the edge. Developer platform is the long-term differentiator.",
    ceo: "Matthew Prince",
    keyProducts: ["Cloudflare Workers (edge compute)", "Zero Trust / SASE", "R2 (object storage)", "AI Gateway / Workers AI"],
    competitors: ["Zscaler (SASE)", "Akamai (CDN)", "AWS CloudFront", "Fastly"],
    moat: "Cloudflare's network of 300+ PoPs covering 95% of internet users creates unmatched latency and resilience. The developer platform (Workers, R2) builds bottom-up adoption in enterprises.",
    keyRisk: "Path to profitability — Cloudflare has been investing heavily in network expansion; FCF margins are improving but remain below software peers. Hyperscaler edge services competition.",
  },
  ZS: {
    description: "Zscaler is the leading cloud-native Zero Trust security platform, replacing traditional VPNs and firewalls with its ZIA (internet access) and ZPA (private access) services delivered from 150+ data centres globally.",
    ceo: "Jay Chaudhuri",
    keyProducts: ["Zscaler Internet Access (ZIA)", "Zscaler Private Access (ZPA)", "Zscaler Digital Experience (ZDX)", "Data Security (DSPM)"],
    competitors: ["Palo Alto Networks (Prisma SASE)", "Cloudflare", "Netskope", "Cisco (Umbrella)"],
    moat: "Zero Trust architecture mandates are being adopted across US federal agencies and Fortune 500 companies — Zscaler's FedRAMP-authorised platform is the default choice for compliant deployments.",
    keyRisk: "Large deal execution risk — Zscaler's average contract value is >$1M, and any slowdown in large enterprise decision-making directly impacts quarter-to-quarter revenue.",
  },
  LLY: {
    description: "Eli Lilly is the dominant GLP-1 drug maker — Mounjaro (tirzepatide) for diabetes and Zepbound for obesity are the fastest-growing drugs in pharmaceutical history. The obesity market alone could reach $150B by 2030.",
    ceo: "David Ricks",
    keyProducts: ["Mounjaro / Zepbound (tirzepatide / GLP-1)", "Verzenio (cancer)", "Kisunla (Alzheimer's)", "Jardiance (diabetes)"],
    competitors: ["Novo Nordisk (Ozempic/Wegovy)", "Amgen (MariTide)", "Pfizer (oral GLP-1)"],
    moat: "Lilly's manufacturing scale for tirzepatide is 18–24 months ahead of any competitor. The clinical pipeline breadth — oncology, Alzheimer's, immunology — reduces GLP-1 concentration risk.",
    keyRisk: "Manufacturing capacity constraints limiting GLP-1 revenue growth vs demand. Drug pricing reform (IRA Medicare negotiations) coming in 2028 for tirzepatide. Novo Nordisk's oral semaglutide competitive threat.",
  },
  ISRG: {
    description: "Intuitive Surgical makes the da Vinci surgical robot system, used in 10 million+ procedures annually across urology, gynecology, thoracic, and colorectal surgery. The system/instrument razor-and-blade model is extremely high-margin.",
    ceo: "Gary Guthart",
    keyProducts: ["da Vinci 5 (robot system)", "Surgical instruments (recurring)", "Ion (lung biopsy)", "Endoscopy platform"],
    competitors: ["Medtronic (Hugo)", "Johnson & Johnson (Ottava)", "CMR Surgical (Versius)"],
    moat: "10,000+ da Vinci systems installed with 2 million trained surgeons create an insurmountable installation base. Surgeons resist switching because robotic surgery skills are system-specific.",
    keyRisk: "J&J Ottava and Medtronic Hugo launching could slow new system placements. Healthcare budget pressures in Europe and Asia may delay robot upgrades. Procedure growth must stay above 12% to justify the valuation.",
  },
  MRK: {
    description: "Merck's lead asset is Keytruda (pembrolizumab), the world's best-selling drug and a PD-1 cancer immunotherapy used in 40+ cancer types. Keytruda generates ~45% of Merck's revenue and faces patent expiry in 2028.",
    ceo: "Robert Davis",
    keyProducts: ["Keytruda (pembrolizumab / PD-1)", "Gardasil (HPV vaccine)", "Winrevair (PAH)", "Sotatercept pipeline"],
    competitors: ["Bristol-Myers Squibb (Opdivo)", "AstraZeneca (Imfinzi)", "Roche (Tecentriq)"],
    moat: "Keytruda's label across 40+ cancer indications and its combination with chemotherapy protocols makes it the default oncologist choice. Switching to a competitor requires new clinical data for each indication.",
    keyRisk: "Keytruda patent cliff in 2028 is an earnings air pocket — Merck needs pipeline assets to replace ~$20B/year in revenue. US IRA drug pricing reform will accelerate Keytruda price erosion post-2028.",
  },
  ABBV: {
    description: "AbbVie's lead product is Skyrizi and Rinvoq (immunology), which are replacing Humira revenue lost to biosimilar competition. Humira generated $20B/year at peak; Skyrizi and Rinvoq are projected to collectively exceed that by 2027.",
    ceo: "Richard Gonzalez",
    keyProducts: ["Skyrizi (risankizumab / IL-23)", "Rinvoq (upadacitinib / JAK)", "Imbruvica (oncology)", "Botox / Juvederm (aesthetics)"],
    competitors: ["Johnson & Johnson (Tremfya)", "Pfizer (Xeljanz biosimilar)", "UCB (Bimekizumab)"],
    moat: "Skyrizi's IL-23 mechanism shows superior efficacy to older IL-12/23 biologics in psoriasis, Crohn's, and UC — creating strong clinical adoption. Allergan aesthetics portfolio (Botox) provides a diversified, high-margin revenue stream.",
    keyRisk: "Humira biosimilar price erosion is accelerating faster than consensus. Rinvoq JAK inhibitor class faces Black Box Warning limiting use in some patient populations, creating a competitive disadvantage vs IL biologics.",
  },
  AMGN: {
    description: "Amgen is a biotech pioneer in biological medicines — Enbrel (rheumatoid arthritis), Prolia (osteoporosis), PCSK9 inhibitors (Repatha), and the emerging obesity drug MariTide (monthly GLP-1/GIPR dual agonist).",
    ceo: "Robert Bradway",
    keyProducts: ["Repatha (PCSK9 / cholesterol)", "Prolia / Xgeva (bone)", "KRAS inhibitors (Lumakras/Sotorasib)", "MariTide (obesity / GLP-1)"],
    competitors: ["AbbVie / J&J (immunology)", "Eli Lilly (GLP-1)", "Regeneron (PCSK9)"],
    moat: "Amgen's 45-year manufacturing experience with complex biological molecules creates a competitive barrier — biosimilar production requires rare expertise. MariTide monthly dosing is a potential differentiator vs weekly Ozempic.",
    keyRisk: "Enbrel and Neulasta revenues declining as biosimilars enter — these legacy drugs generate ~25% of revenue. MariTide needs Phase 3 data to validate the obesity opportunity vs Lilly/Novo Nordisk.",
  },
  JPM: {
    description: "JPMorgan Chase is the world's largest bank by market capitalisation, with dominant positions in investment banking, commercial banking, consumer banking, and asset management. CEO Jamie Dimon is viewed as the most capable banker of his generation.",
    ceo: "Jamie Dimon",
    keyProducts: ["Investment Banking (M&A, ECM, DCM)", "Consumer Banking / Chase", "Commercial Banking / Treasury", "Asset & Wealth Management"],
    competitors: ["Goldman Sachs", "Morgan Stanley", "Bank of America", "Wells Fargo"],
    moat: "JPMorgan's fortress balance sheet, technology investment ($17B/year IT spend), and client relationships across all market segments make it the 'must-have' counterparty for Fortune 500 companies.",
    keyRisk: "Net interest income compression as Fed cuts rates. Commercial real estate credit exposure. Increased capital requirements under Basel III endgame would reduce ROTCE by ~1-2 percentage points.",
  },
  WMT: {
    description: "Walmart is the world's largest retailer by revenue, operating 10,500+ stores in 19 countries plus Walmart.com and Sam's Club. The advertising business (Walmart Connect) and marketplace are the highest-margin growth opportunities.",
    ceo: "Doug McMillon",
    keyProducts: ["Walmart.com / Marketplace", "Sam's Club", "Walmart Connect (advertising)", "Walmart+ Membership"],
    competitors: ["Amazon (e-commerce)", "Costco (membership retail)", "Target", "Dollar General (low income)"],
    moat: "Supply chain scale ($600B+ revenue) enables pricing power impossible for smaller retailers. Walmart+ and the advertising business create high-margin revenue streams that subsidise everyday low prices.",
    keyRisk: "E-commerce profitability remains elusive — Walmart still loses money on last-mile delivery. Amazon's scale in e-commerce makes it difficult for Walmart to close the gap in product selection and delivery speed.",
  },
  QCOM: {
    description: "Qualcomm designs Snapdragon mobile processors and 5G modems used in Android smartphones and, increasingly, Windows PCs (Snapdragon X Elite). Its licensing business (QTL) is a high-margin royalty stream on virtually every 5G phone.",
    ceo: "Cristiano Amon",
    keyProducts: ["Snapdragon 8 Elite (mobile SoC)", "Snapdragon X Elite (PC)", "QTL licensing (5G royalties)", "Automotive (Snapdragon Digital Chassis)"],
    competitors: ["MediaTek (mobile SoC)", "Apple (in-house chips)", "Intel (PC chips)", "ARM ecosystem"],
    moat: "QTL licensing covers 5G standard-essential patents — every 5G phone in the world pays Qualcomm a royalty regardless of which chip is inside. This is one of the highest-margin businesses in technology.",
    keyRisk: "Apple designing its own 5G modem (Exynos partnership with TSMC) will eliminate Apple royalties by 2027 — Apple accounts for ~20% of QTL revenue. Samsung reducing Snapdragon orders.",
  },
  AVGO: {
    description: "Broadcom is a semiconductor and infrastructure software company. Its AI networking chips (custom AI ASICs for Google and Meta) and VMware software are the two key growth engines after the $69B VMware acquisition.",
    ceo: "Hock Tan",
    keyProducts: ["AI Networking ASICs (Google / Meta)", "Ethernet switches (Tomahawk/Trident)", "VMware (enterprise virtualisation)", "Wi-Fi / Bluetooth chips"],
    competitors: ["Marvell (AI ASICs)", "Cisco (networking)", "AMD / NVIDIA (GPU)", "Intel (x86 / network)"],
    moat: "Custom AI ASIC design relationships with hyperscalers (Google TPU, Meta MTIA) are multi-year design cycles — once Broadcom wins a socket, it holds it for 3–5 years. VMware revenue adds durable recurring software revenue.",
    keyRisk: "VMware enterprise license revenue recognition creates near-term lumpiness. Customers pushing back on VMware price increases post-acquisition. Custom ASIC market share risk if Google / Meta bring design in-house.",
  },
  INTC: {
    description: "Intel designs and manufactures CPUs (Core, Xeon) and is pursuing an IDM 2.0 strategy to become a contract chipmaker (Intel Foundry Services) competing with TSMC and Samsung. The foundry turnaround is the central investment thesis.",
    ceo: "Pat Gelsinger",
    keyProducts: ["Core Ultra (client CPU)", "Xeon Scalable (data centre)", "Intel Foundry Services (IFS)", "Gaudi AI Accelerator"],
    competitors: ["AMD (CPUs)", "TSMC (foundry)", "NVIDIA (AI accelerators)", "Arm / Qualcomm (client CPU)"],
    moat: "Intel's integrated design-manufacturing model historically enabled rapid iteration. x86 software compatibility on Windows and Linux creates a 45-year installed base of applications.",
    keyRisk: "Intel is fighting on four fronts simultaneously: client CPU (AMD share gains), data centre CPU (AMD EPYC), AI accelerator (NVIDIA dominance), and foundry (vs TSMC). Burning ~$20B/year in capex with uncertain returns.",
  },
  AMD: {
    description: "AMD designs CPUs (EPYC for servers, Ryzen for PCs) and GPUs (Radeon, MI300X for AI). The MI300X data centre GPU is AMD's primary AI challenge to NVIDIA, with $5B+ in annual revenue and growing.",
    ceo: "Lisa Su",
    keyProducts: ["EPYC Genoa/Turin (server CPU)", "MI300X / MI350 (AI GPU)", "Ryzen (client CPU)", "RDNA gaming GPU"],
    competitors: ["Intel (CPU)", "NVIDIA (GPU/AI)", "Qualcomm (Arm CPU)"],
    moat: "EPYC server CPU has taken 24%+ share from Intel in data centre — AMD's per-core performance/TCO advantage is well-documented. MI300X's HBM bandwidth advantage over H100 is real for large-model inference.",
    keyRisk: "CUDA software ecosystem moat means most AI training workloads will not move to MI300X regardless of hardware specs. AMD needs ROCm software to improve dramatically to win AI training market share.",
  },
  SPGI: {
    description: "S&P Global provides credit ratings, market intelligence (Platts energy data), financial data (S&P DJI indices), and regulatory workflow software (Compliance / Risk). The Dow Jones Indices business earns recurring royalties on $10 trillion in ETF AUM.",
    ceo: "Doug Peterson",
    keyProducts: ["S&P 500 / DJI Indices (ETF royalties)", "Credit Ratings (SPGI Ratings)", "Market Intelligence data", "Platts energy data"],
    competitors: ["Moody's (ratings)", "MSCI (indices)", "Bloomberg (data)", "FactSet"],
    moat: "S&P 500 index is the most-tracked benchmark in finance — every ETF tracking it pays royalties. Credit ratings carry regulatory weight that is quasi-mandated by securities law across 130 countries.",
    keyRisk: "Bond issuance slowdown (rates are high, M&A depressed) directly reduces ratings revenue. Regulatory pressure on rating agency oligopoly (EU Competition investigation). IHSMarkit integration remaining synergy delivery.",
  },
  SQ: {
    description: "Block (formerly Square) operates the Square seller ecosystem (POS, payments, lending) and Cash App (P2P money transfer, Bitcoin, investing). Cash App's monetisation and BNPL (Afterpay) are the key growth opportunities.",
    ceo: "Jack Dorsey",
    keyProducts: ["Cash App (P2P / Bitcoin / investing)", "Square POS / Payment Processing", "Square Banking / Capital (SMB lending)", "Afterpay (BNPL)"],
    competitors: ["PayPal (Venmo)", "Stripe (SMB payments)", "Shopify (e-commerce POS)", "Klarna (BNPL)"],
    moat: "Cash App's 57 million monthly actives with a free-to-use P2P model create a distribution platform that Block is now monetising through banking, investing, and Bitcoin. Square's card reader became the de facto SMB payment solution.",
    keyRisk: "Cash App monetisation growth slowing relative to user growth expectations. Bitcoin price volatility creates lumpy gross profit. Afterpay underperforming — BNPL credit losses elevated in high-rate environment.",
  },
  MELI: {
    description: "MercadoLibre is Latin America's largest e-commerce and fintech company, operating the Mercado Pago payment wallet, Mercado Envios logistics, and the core marketplace across Brazil, Argentina, and Mexico.",
    ceo: "Marcos Galperin",
    keyProducts: ["Mercado Pago (fintech / BNPL / card)", "Marketplace (18 countries)", "Mercado Credito (lending)", "Mercado Envios (logistics)"],
    competitors: ["Amazon (Brazil e-commerce)", "Rappi / iFood (Brazil quick commerce)", "Nubank (fintech)", "PayPal (Latin America)"],
    moat: "MercadoLibre's network effects across 18 Latin American countries with 90M+ active buyers are nearly impossible to replicate. Mercado Pago's TPV ($64B+) gives it the scale for credit underwriting no other Latin American fintech matches.",
    keyRisk: "Currency devaluation in Argentina (hyperinflation) and Brazil creates FX headwinds on US-reported earnings. Amazon Brazil is investing aggressively in marketplace and logistics competition.",
  },
  NU: {
    description: "Nubank is the world's largest digital bank by customers (100M+), operating in Brazil, Mexico, and Colombia. It operates a mobile-first banking model with zero physical branches and industry-leading NPS scores.",
    ceo: "David Vélez",
    keyProducts: ["Nubank Credit Card (no fee)", "Nu Conta (digital account)", "NuInvest (investments)", "Nu+ / NuLife (premium)"],
    competitors: ["Itaú Unibanco (Brazil incumbents)", "Bradesco", "MercadoPago", "Inter (Brazilian digital bank)"],
    moat: "Nubank's 100M customer base at a <$10 cost-to-serve vs $150+ for Brazilian incumbents creates an unbeatable unit economics advantage. Word-of-mouth growth eliminates customer acquisition costs.",
    keyRisk: "Brazil credit cycle risk — if unemployment rises, Nubank's unsecured credit book could face elevated defaults. Market saturation in Brazil means growth depends on Mexico/Colombia monetisation, which is earlier-stage.",
  },
  ASML: {
    description: "ASML is the sole manufacturer of Extreme Ultraviolet (EUV) lithography machines used to make the world's most advanced semiconductor chips. Its High-NA EUV machines (required for sub-2nm chips) cost $380M each — and ASML is the only supplier.",
    ceo: "Christophe Fouquet",
    keyProducts: ["EUV lithography machines (TWINSCAN NXE)", "High-NA EUV (TWINSCAN EXE)", "Deep UV (ArFi) systems", "Metrology and Inspection"],
    competitors: ["None (monopoly in EUV/High-NA). Nikon and Canon compete only in older DUV technology."],
    moat: "ASML has a literal global monopoly on EUV machines. The technology is so complex (10,000 suppliers, 457 patents) that it took 30 years to develop. No competitor is within a decade of matching it.",
    keyRisk: "Dutch export controls restricting EUV sales to China directly reduce addressable market. Any slowdown in hyperscaler AI chip buildout directly reduces ASML order backlog. High-NA ramp slower than expected.",
  },
  TSM: {
    description: "TSMC (Taiwan Semiconductor Manufacturing Company) is the world's leading contract chipmaker, fabricating chips for Apple, NVIDIA, AMD, Qualcomm, and hundreds of others. Its N3 (3nm) and N2 (2nm) nodes are critical to global AI infrastructure.",
    ceo: "C.C. Wei",
    keyProducts: ["N3 / N2 (advanced process nodes)", "CoWoS packaging (AI chip stacking)", "N5 / N4 (HPC and mobile)", "Arizona fab expansion (N2)"],
    competitors: ["Samsung Foundry", "Intel Foundry Services", "SMIC (China, lagging)"],
    moat: "TSMC has 90%+ share of the leading-edge (<5nm) foundry market. Its manufacturing yield rates are 15–20 percentage points higher than Samsung Foundry — this is a skill advantage accumulated over 35 years.",
    keyRisk: "Taiwan geopolitical risk (China invasion scenario) is the ultimate tail risk — TSMC's Taiwan fabs produce 90% of the world's leading-edge chips. Any armed conflict would catastrophically disrupt global semiconductor supply.",
  },
  ARM: {
    description: "Arm Holdings licenses its processor instruction set architecture (ISA) and CPU designs (Cortex-A, Neoverse) that power virtually every smartphone chip, and increasingly AI data centre chips (Neoverse). Royalties accrue on billions of chips shipped annually.",
    ceo: "Rene Haas",
    keyProducts: ["Armv9 ISA (instruction set)", "Cortex-A / Cortex-X (mobile CPUs)", "Neoverse (data centre / AI)", "Mali GPU designs"],
    competitors: ["RISC-V open-source ISA (emerging)", "x86 (Intel/AMD, PC/server)"],
    moat: "Arm's ISA is the instruction set for 99% of smartphones globally — every chip maker (Apple M-series, Qualcomm Snapdragon, MediaTek Dimensity, Google Tensor) is licensed. Switching away would require recompiling every mobile app.",
    keyRisk: "RISC-V open-source ISA gradually gaining traction could reduce Arm's future licensing power in embedded/IoT markets. Arm's royalty rates are a fraction of chip ASP — any push to raise them faces customer resistance.",
  },
  SAP: {
    description: "SAP is the world's leading enterprise resource planning (ERP) software vendor, running core business processes (finance, HR, supply chain) for 99 of the 100 largest companies. Its cloud transition (S/4HANA Cloud) is the defining multi-year investment thesis.",
    ceo: "Christian Klein",
    keyProducts: ["S/4HANA Cloud (ERP)", "SuccessFactors (HR)", "Ariba (procurement)", "Business AI / Joule (copilot)"],
    competitors: ["Oracle (Fusion ERP)", "Microsoft Dynamics", "Workday (HR)"],
    moat: "SAP ERP is embedded in the business operations of 400,000 companies across 180 countries. Switching costs are years of implementation work and business disruption — making SAP one of the stickiest enterprise software platforms.",
    keyRisk: "Cloud migration slower than expected — many customers still run on-premise S/4HANA, and the S/4HANA Cloud transition requires expensive consulting engagements. Oracle gaining ERP share in mid-market.",
  },
  RACE: {
    description: "Ferrari designs and manufactures ultra-luxury sports cars and grand tourers priced $250,000–$3.5M+. It is structurally capacity-constrained — Ferrari intentionally limits production to preserve brand exclusivity. Formula 1 is its global marketing engine.",
    ceo: "Benedetto Vigna",
    keyProducts: ["Ferrari Roma / Purosangue (SUV)", "SF90 / SF90 XX (hybrid hypercar)", "LaFerrari limited editions", "Personalisation / Tailor-Made"],
    competitors: ["Lamborghini (Ducati/VW)", "McLaren", "Aston Martin (Limited)"],
    moat: "Ferrari deliberately restricts supply below demand — average 2-year wait list. Personalisation revenue per car is growing faster than base car revenue. The Ferrari brand is arguably the world's most valuable luxury brand per unit.",
    keyRisk: "Hybrids introduce more complexity — Ferrari's first fully-electric car (Adrenaline) launches in 2025 and may not deliver the same driver experience that justifies premium pricing. China luxury slowdown.",
  },
  LVMUY: {
    description: "LVMH (Moët Hennessy Louis Vuitton) is the world's largest luxury conglomerate, owning 75+ brands including Louis Vuitton, Dior, Bulgari, Tiffany, Hennessy, and Dom Pérignon across fashion, leather goods, spirits, and jewellery.",
    ceo: "Bernard Arnault",
    keyProducts: ["Louis Vuitton (fashion / leather)", "Christian Dior Couture", "Hennessy Cognac", "Tiffany & Co.", "Sephora (beauty retail)"],
    competitors: ["Kering (Gucci / Saint Laurent)", "Hermès (handbags)", "Richemont (jewellery)", "Estée Lauder (beauty)"],
    moat: "Louis Vuitton generates ~12B+ in revenue at >40% operating margins — this is the highest-margin fashion business in history. The LV monogram is a global status signal that transcends geography and generation.",
    keyRisk: "China luxury demand slowdown is the #1 near-term risk — Chinese consumers represent ~40% of global luxury spending. Aspirational buyer pull-back in US/Europe. Succession risk as Bernard Arnault approaches 76.",
  },
  RELX: {
    description: "RELX is a UK-listed information and analytics company operating four divisions: Scientific publishing (Elsevier), Legal research (LexisNexis), Risk analytics (Cirium, HESA), and Exhibitions. All four divisions are growing in low-to-mid single digits with exceptional margins.",
    ceo: "Erik Engstrom",
    keyProducts: ["Elsevier / ScienceDirect (research)", "LexisNexis (legal data)", "Reed Risk Analytics", "ReedPop / Events"],
    competitors: ["Clarivate (research analytics)", "Thomson Reuters (legal)", "Wolters Kluwer"],
    moat: "Scientific journals have a network effect: authors want to publish in prestigious journals, and journals gain prestige from citation counts. LexisNexis legal databases are embedded in the workflows of every major law firm.",
    keyRisk: "Open-access publishing movement (Plan S) challenging the Elsevier paid-journal model. AI-generated research summaries could reduce the need for journal subscriptions. Regulatory scrutiny of academic journal pricing.",
  },
  PEP: {
    description: "PepsiCo operates two major divisions: Beverages (Pepsi, Gatorade, Mountain Dew, Lipton) and Convenient Foods (Lay's, Doritos, Quaker). Frito-Lay North America is the highest-margin segment and the real earnings engine.",
    ceo: "Ramon Laguarta",
    keyProducts: ["Frito-Lay (Lay's, Doritos, Cheetos)", "Gatorade / Powerade (sports drinks)", "Pepsi-Cola / Mountain Dew", "Quaker oats / ready-to-eat"],
    competitors: ["Coca-Cola (beverages)", "Kellogg's (snacks)", "Campbell's", "Monster Beverage"],
    moat: "Frito-Lay's direct-store-delivery (DSD) system delivers chips to 200,000+ US retail locations weekly — this logistics infrastructure took 60 years to build and is impossible to replicate at cost.",
    keyRisk: "GLP-1 drugs (Ozempic/Mounjaro) reducing snack and beverage consumption is the new structural headwind. Volume declines in salty snacks as consumers trade to healthier options. Private label competition in beverages.",
  },
  KO: {
    description: "Coca-Cola is the world's largest non-alcoholic beverage company, selling 2 billion+ servings per day across 200+ countries. It operates an asset-light franchise model where independent bottlers do manufacturing/distribution — Coke just sells concentrate.",
    ceo: "James Quincey",
    keyProducts: ["Coca-Cola / Coke Zero / Diet Coke", "Sprite / Fanta (multi-country)", "Fairlife (milk / protein)", "Simply / Minute Maid (juices)"],
    competitors: ["PepsiCo", "Dr Pepper / Keurig", "Nestlé (water)", "Monster / Red Bull (energy)"],
    moat: "Coke's 200-country franchise bottler network is a distribution moat that took 120 years to build. The Coke brand generates pricing power across every income demographic and geography on earth.",
    keyRisk: "GLP-1 drug penetration reducing sugary drink consumption is the 10-year secular headwind. Sugar taxes and health warnings spreading globally. Fairlife and growth brands (Topo Chico) need to offset core CSDs.",
  },
  JNJ: {
    description: "Johnson & Johnson operates in Pharmaceutical (Darzalex, Tremfya, Stelara) and MedTech (Depuy Synthes, Electrophysiology, Vision). The consumer division was spun off as Kenvue in 2023.",
    ceo: "Joaquin Duato",
    keyProducts: ["Darzalex (multiple myeloma)", "Tremfya / Stelara (immunology)", "Depuy Synthes (orthopaedics)", "Abiomed (heart pumps)"],
    competitors: ["AbbVie / Pfizer (immunology)", "Medtronic (MedTech)", "Stryker (orthopaedics)"],
    moat: "J&J's AAA credit rating and 60-year dividend growth streak reflect the quality of its diversified cash flows. Multi-billion-dollar platforms across immunology, oncology, and MedTech create revenue stability.",
    keyRisk: "Talc litigation liability (baby powder asbestos claims) — J&J's third bankruptcy attempt for LTL Management is under appeal. Stelara biosimilar entrants in 2025 will erode a $10B/year product.",
  },
  HUBS: {
    description: "HubSpot is the leading CRM platform for small and mid-market businesses (SMBs), providing marketing automation, sales CRM, customer service, and content management in one fully integrated suite.",
    ceo: "Yamini Rangan",
    keyProducts: ["HubSpot Marketing Hub", "HubSpot Sales Hub (CRM)", "HubSpot Service Hub", "HubSpot Breeze AI (copilot)"],
    competitors: ["Salesforce (enterprise CRM)", "Zoho CRM (SMB)", "ActiveCampaign (marketing)"],
    moat: "HubSpot's 'flywheel' model integrates marketing, sales, and service data in one platform — SMBs avoid the costly integrations required with point solutions. Annual NPS of 49+ demonstrates extraordinary customer satisfaction.",
    keyRisk: "Market saturation in core US SMB segment driving growth to international markets (lower ACV). Salesforce and Microsoft adding SMB CRM features at lower price points. AI agents from competitors reducing switching friction.",
  },
  CRSP: {
    description: "CRISPR Therapeutics is a gene-editing biotech that developed Casgevy — the world's first CRISPR-based medicine, FDA-approved for sickle cell disease and beta-thalassaemia (joint with Vertex). The pipeline includes in-vivo gene editing programmes.",
    ceo: "Sam Kulkarni",
    keyProducts: ["Casgevy (exa-cel / sickle cell / beta-thal)", "CTX310 (ATTR amyloidosis)", "CTX320 (Lp(a) / cardiovascular)", "In vivo CRISPR pipeline"],
    competitors: ["Beam Therapeutics (base editing)", "Intellia Therapeutics (in-vivo)", "Vertex (Casgevy partner)"],
    moat: "First-mover advantage with the world's only approved CRISPR medicine. Foundational CRISPR patents provide IP protection for core gene-editing approaches. Vertex partnership provides manufacturing and commercial infrastructure.",
    keyRisk: "Casgevy's $2.2M price and complex one-time treatment logistics limit patient uptake — commercial ramp is slower than hoped. Multiple CRISPR patent disputes with the Broad Institute create litigation uncertainty.",
  },
  VRTX: {
    description: "Vertex Pharmaceuticals dominates cystic fibrosis treatment — its trikafta/Kaftrio combination treats 90% of CF patients and has essentially no competition. The next growth phase is pain management (suzetrigine, Nav1.8 inhibitor) and AATD.",
    ceo: "Reshma Kewalramani",
    keyProducts: ["Trikafta / Kaftrio (cystic fibrosis)", "Casgevy (sickle cell, CRISPR)", "Suzetrigine (pain / Nav1.8)", "VX-880 (Type 1 diabetes)"],
    competitors: ["AbbVie (CF pipeline, early-stage)", "Forma Therapeutics (AATD)"],
    moat: "Vertex has a near-monopoly in cystic fibrosis — trikafta is prescribed for 90% of CF patients and there is no competitive challenge in sight. CF patient lifetime value exceeds $1 million per patient treated.",
    keyRisk: "Cystic fibrosis market is finite (~80,000 patients globally) — Vertex needs suzetrigine and diabetes pipeline to drive the next growth phase. Pain drug competition is intense (Pfizer, Lilly developing Nav1.8 inhibitors).",
  },
  REGN: {
    description: "Regeneron discovered Dupixent (dupilumab), the world's best-selling biologic for atopic dermatitis, asthma, and COPD — with a potential $20B+ peak revenue. Its VEGF Trap platform (Eylea, Zaltrap) provides durable ophthalmology revenue.",
    ceo: "Leonard Schleifer",
    keyProducts: ["Dupixent (dupilumab / atopic dermatitis / asthma)", "Eylea / Eylea HD (macular degeneration)", "Kevzara (rheumatoid arthritis)", "Libtayo (PD-1 / oncology)"],
    competitors: ["AstraZeneca / Sanofi (tezepelumab / asthma)", "AbbVie (RINVOQ / atopic dermatitis)", "Roche / Genentech (VEGF / ophthalmology)"],
    moat: "Dupixent's IL-4/IL-13 dual blockade mechanism has shown efficacy across 10+ inflammatory diseases — each new indication adds incremental revenue from existing manufacturing. Regeneron's VelociGene discovery engine has a 40+ year track record.",
    keyRisk: "Eylea facing biosimilar competition from Amgen's Pavblu — Eylea generates ~$5B/year. Dupixent in atopic dermatitis faces increasing competition from JAK inhibitors (Rinvoq, Olumiant) in moderate cases.",
  },
};

/** Company-level intelligence fallback when ticker not found */
export function getCompanyIntel(ticker: string, sector?: string, industry?: string): CompanyIntel | null {
  return INTEL[ticker] ?? null;
}

export { INTEL };
